// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(WriteDataContext))]
    partial class WriteDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.People.PeopleAggregate.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("char")
                        .HasColumnName("external_id");

                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("person_id");

                    b.HasKey("Id")
                        .HasName("pk_document");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_document_person_id");

                    b.ToTable("document", (string)null);
                });

            modelBuilder.Entity("Domain.Models.People.PeopleAggregate.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("char")
                        .HasColumnName("external_id");

                    b.HasKey("Id")
                        .HasName("pk_person");

                    b.ToTable("person", (string)null);
                });

            modelBuilder.Entity("Domain.Models.People.PeopleAggregate.Entities.Document", b =>
                {
                    b.HasOne("Domain.Models.People.PeopleAggregate.Entities.Person", "Person")
                        .WithMany("Documents")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_document_person_person_id");

                    b.OwnsOne("Domain.Models.People.PeopleAggregate.ValueObjects.Document.IssuerValue", "Issuer", b1 =>
                        {
                            b1.Property<int>("DocumentId")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar")
                                .HasColumnName("issuer_value");

                            b1.HasKey("DocumentId");

                            b1.ToTable("document");

                            b1.WithOwner()
                                .HasForeignKey("DocumentId")
                                .HasConstraintName("fk_document_document_id");
                        });

                    b.OwnsOne("Domain.Models.People.PeopleAggregate.ValueObjects.Document.ValueValue", "Value", b1 =>
                        {
                            b1.Property<int>("DocumentId")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar")
                                .HasColumnName("value_value");

                            b1.HasKey("DocumentId");

                            b1.ToTable("document");

                            b1.WithOwner()
                                .HasForeignKey("DocumentId")
                                .HasConstraintName("fk_document_document_id");
                        });

                    b.Navigation("Issuer")
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Value")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.People.PeopleAggregate.Entities.Person", b =>
                {
                    b.OwnsOne("Domain.Models.People.PeopleAggregate.ValueObjects.Person.FirstNameValue", "FirstName", b1 =>
                        {
                            b1.Property<int>("PersonId")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar")
                                .HasColumnName("first_name_value");

                            b1.HasKey("PersonId");

                            b1.ToTable("person");

                            b1.WithOwner()
                                .HasForeignKey("PersonId")
                                .HasConstraintName("fk_person_person_id");
                        });

                    b.OwnsOne("Domain.Models.People.PeopleAggregate.ValueObjects.Person.LastNameValue", "LastName", b1 =>
                        {
                            b1.Property<int>("PersonId")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar")
                                .HasColumnName("last_name_value");

                            b1.HasKey("PersonId");

                            b1.ToTable("person");

                            b1.WithOwner()
                                .HasForeignKey("PersonId")
                                .HasConstraintName("fk_person_person_id");
                        });

                    b.OwnsOne("Domain.Models.People.PeopleAggregate.ValueObjects.Person.MiddleNameValue", "MiddleName", b1 =>
                        {
                            b1.Property<int>("PersonId")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar")
                                .HasColumnName("middle_name_value");

                            b1.HasKey("PersonId");

                            b1.ToTable("person");

                            b1.WithOwner()
                                .HasForeignKey("PersonId")
                                .HasConstraintName("fk_person_person_id");
                        });

                    b.Navigation("FirstName")
                        .IsRequired();

                    b.Navigation("LastName")
                        .IsRequired();

                    b.Navigation("MiddleName");
                });

            modelBuilder.Entity("Domain.Models.People.PeopleAggregate.Entities.Person", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
